### ISSUE TITLE
Interpretable TimeVAE evaluation

### ISSUE THREAD

**Issue by franciscogaluppo** [abudesai/timeVAE#1]
Firstly, thank you for the code, using [test_vae.py](https://github.com/abudesai/timeVAE/blob/main/test_vae.py) was straightforward. I've just read the [paper](https://openreview.net/forum?id=VDdDvnwFoyM) and was wondering:
  1. if there is any comparison between the Interpretable TimeVAE and the other models (Base TimeVAE, TimeGAN, T-Forcing, RCGAN);
  2. if there is any example of the use of the interpretability feature in some real data.

Thank you once again.

**Comment by abudesai** [comment]
Hi Francisco,
Thank you for your email.
Regarding question 1, we could not finish the comparisons of the
Interpretable TimeVAE with other methods because we ran out of time on the
project, and had to move on to other projects (we are in industry, not
academia). The limited experiments we did showed the results were
comparable (slightly worse, but not by much). That was expected by us
because constraining the model would be expected to cause equal or worse
performance, not better. Unfortunately, we don't have the results saved so
I cannot get them to you. I no longer work at the company.

The goal of the interpretable model was to allow users to impose domain
specific structure which would make the model more easy to explain. It was
more about explainability, less about getting a more accurate model. But
again, the results didn't show any material degradation in performance.

Regarding question 2, I don't have an example ready, but I can create one
for you. Can you explain what you need exactly in terms of an example, and
when you need it by?

Thanks.
Abu Desai

**Comment by abudesai** [comment]
Closing this issue - I assume your issue is resolved.
